<meta charset="utf-8">
<meta http-http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="CSS/Nav.CSS">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Cairo&display=swap" rel="stylesheet">
  <nav class="fixed-top .row">
    <div class="nav .col-xs-4">

                <div> <a href="Register-Login.PHP">  LOGIN - REGISTER</a> </div>
                <div> <a href="Home.PHP">            HOME            </a> </div>
                <div> <a href="Myself.PHP">          MY PROFILE      </a> </div>
                <div> <a href="Friends.PHP">         MY FRIENDS      </a> </div>
                <div> <a href="Support.PHP">         SUPPORT         </a> </div>
                <div> <a href="Settings.PHP">        SETTINGS        </a> </div>
    </div>
  </nav>
