<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link href="https://fonts.googleapis.com/css?family=Cairo&display=swap" rel="stylesheet">
        <title>Settings</title>
         <link rel="stylesheet" href="CSS/Settings.css">

  </head>
  <body>
    <div class="container">
     <header>
      <h1>Settings</h1>
      <h5><a href="Home.PHP" class="center leave">Save changes and leave this place... </a></h5>
     </header>
<section>
  <article class="conf">
    <ul type="I" id="ez">
      <li><a href="#">Customize</a></li>
      <li><a href="#">Notifications-Alerts</a></li>
      <li><a href="#">Change your tag</a></li>
      <li><a href="#">Change your Mail</a></li>
      <li><a href="#">New password</a></li>
      <li><a href="#">Blocked users</a></li>
      <li><a href="#">Freeze your account</a></li>
    </ul>
  </article>
</section>

     <footer>

     </footer>
    </div>
  </body>
</html>
