<?php $marquee = "It seems like you need some help..." ?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="CSS/Support.CSS">
    <link rel="stylesheet" href="Require/CSS/Nav.CSS">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cairo&display=swap" rel="stylesheet">
    <title>FAQ - I AM</title>
  </head>
  <body>
    <?php require_once("Require/Nav.PHP");?>
    <?php require_once("Require/Header.PHP") ;?>
<div class="Body white center">

      <h2>Support</h2>
      <br>
      <div class="Question">Whats wrong?<br>
              <br>
                  <textarea class="textarea"name="name" rows="8" cols="5" placeholder="Tell us here!"></textarea>
              <br>
      </div>
      <br>
      <br>
  <footer>
      Do ya' need help?
      <br> <a href="Support.HTML">CONTACT SUPPORT HER... Oh wait, you are now here... </a>
      <br> <a href="FAQ.HTML">SEE THE FAQ HERE</a>
      <p><marquee> Why are you still here?</marquee></p>
  </footer>
</body>
</html>
